language: python

python:
    - '3.6'
    - '3.7'
    - '3.8'

install: pip install -e ."[dev]"

script: 
    - flake8 algorithms/*.py
    - flake8 test/*.py
    - pytest --cov=algorithms --cov-branch

after_success:
    - coveralls
